name: Build Windows 9x QuickInstall

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Permite executar o workflow manualmente pela interface do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "git://"
      - uses: actions/checkout@v3
        with:
          submodules: false
      - name: Update submodules manually
        run: |
          git submodule init
          git submodule update --init --recursive --depth=1 || echo "Some submodules may have failed, continuing anyway"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage p7zip-full wine
          python -m pip install --upgrade pip
          # Usar o arquivo requirements.txt do diretório sysprep
          pip install -r sysprep/requirements.txt

      - name: Build ISO
        run: |
          # Verificar se existem diretórios necessários ou criá-los
          mkdir -p _OS_ROOT_ _DRIVER_ _EXTRA_DRIVER_ _EXTRA_CD_FILES_ _OUTPUT_
          
          # Executar o script de preparação (ajuste conforme necessário)
          python sysprep.py --verbose True || echo "Build process may have encountered issues"
          
          # Criar um arquivo de informações sobre a build
          echo "Build date: $(date)" > _OUTPUT_/build_info.txt
          echo "Git commit: $(git rev-parse HEAD)" >> _OUTPUT_/build_info.txt
          echo "Git branch: $(git rev-parse --abbrev-ref HEAD)" >> _OUTPUT_/build_info.txt

      - name: Package artifacts
        run: |
          # Criar um arquivo ZIP com todo o conteúdo do _OUTPUT_
          cd _OUTPUT_
          zip -r ../win98-quickinstall-build.zip ./*
          cd ..

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: win98-quickinstall-output
          path: _OUTPUT_
          
      - name: Upload packaged build
        uses: actions/upload-artifact@v4
        with:
          name: win98-quickinstall-build
          path: win98-quickinstall-build.zip