name: Build Windows 9x QuickInstall

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Permite executar o workflow manualmente pela interface do GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "git://"
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fix submodule URLs and update
        run: |
          # Substituir URLs SSH por HTTPS no arquivo .gitmodules
          if [ -f ".gitmodules" ]; then
            sed -i 's|git@github.com:|https://github.com/|g' .gitmodules
            sed -i 's|git://|https://|g' .gitmodules
            cat .gitmodules
          fi
          
          # Inicializar e atualizar submodules um por um
          git submodule init
          
          # Listar todos os submodules
          git config --file .gitmodules --get-regexp path | awk '{ print $2 }' | while read path; do
            echo "Atualizando submodule: $path"
            git submodule update --init --depth=1 "$path" || echo "Failed to update $path, continuing anyway"
          done
          
      - name: Create framework package
        run: |
          # Criar um diretório para o pacote completo
          mkdir -p win98-quickinstall-framework
          
          # Copiar arquivos importantes para o pacote
          cp -r sysprep/ win98-quickinstall-framework/ || echo "sysprep directory not found"
          
          # Copiar diretórios importantes
          mkdir -p win98-quickinstall-framework/_OS_ROOT_
          mkdir -p win98-quickinstall-framework/_DRIVER_
          mkdir -p win98-quickinstall-framework/_EXTRA_DRIVER_
          mkdir -p win98-quickinstall-framework/_EXTRA_CD_FILES_
          mkdir -p win98-quickinstall-framework/_OUTPUT_
          
          # Copiar a pasta cdromroot e seus subdiretórios, incluindo bin
          if [ -d "cdromroot" ]; then
            cp -r cdromroot/ win98-quickinstall-framework/
            echo "Copiada pasta cdromroot e seus subdiretórios"
          else
            echo "Pasta cdromroot não encontrada"
            # Criar a estrutura mínima
            mkdir -p win98-quickinstall-framework/cdromroot/bin
          fi
          
          # Verificar se existem arquivos binários em outros locais
          if [ -d "__BIN__" ]; then
            cp -r __BIN__/ win98-quickinstall-framework/
            echo "Copiada pasta __BIN__"
          fi
          
          cp *.md win98-quickinstall-framework/ || echo "No markdown files found"
          
          # Criar um arquivo README específico para o pacote
          cat > win98-quickinstall-framework/PACKAGE_README.txt << EOF
Windows 9x QuickInstall Framework Package
========================================

Este pacote contém o framework do Windows 9x QuickInstall.
Para usar, você precisa:

1. Colocar os arquivos de um sistema Windows 98/ME já instalado na pasta _OS_ROOT_
2. Colocar drivers a serem integrados na pasta _DRIVER_
3. Colocar drivers extras na pasta _EXTRA_DRIVER_
4. Colocar arquivos extras para o CD na pasta _EXTRA_CD_FILES_
5. Executar o script sysprep.py para criar uma ISO:
   python sysprep.py --iso win98-quickinstall.iso

Consulte o README.md para instruções detalhadas.
EOF
          
          # Criar um arquivo ZIP com o pacote
          zip -r win98-quickinstall-framework.zip win98-quickinstall-framework/
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage p7zip-full wine
          python -m pip install --upgrade pip
          pip install -r sysprep/requirements.txt || echo "Requirements file not found"
          
      - name: Check repository structure
        run: |
          echo "Repository structure:"
          ls -la
          echo "Looking for sysprep.py:"
          find . -name "sysprep.py"
          echo "Checking sysprep directory:"
          ls -la sysprep/ || echo "sysprep directory not found"
          
      - name: Prepare build environment
        run: |
          # Verificar se existem diretórios necessários ou criá-los
          mkdir -p _OS_ROOT_ _DRIVER_ _EXTRA_DRIVER_ _EXTRA_CD_FILES_ _OUTPUT_
          
          # Criar um diretório OS_ROOT mínimo para teste
          mkdir -p _OS_ROOT_/WINDOWS
          touch _OS_ROOT_/WINDOWS/WIN.COM
          
          # Verificar qual é o caminho correto do script sysprep.py
          SYSPREP_PATH=$(find . -name "sysprep.py" | head -1)
          if [ -z "$SYSPREP_PATH" ]; then
            echo "Não foi possível encontrar o script sysprep.py"
            exit 1
          fi
          
          echo "Encontrado script sysprep.py em: $SYSPREP_PATH"
          
          # Não vamos tentar criar uma ISO, apenas preparar os arquivos
          echo "Pulando a criação da ISO, apenas preparando os arquivos do framework"
          
          # Criar um arquivo de informações sobre a build
          echo "Build date: $(date)" > _OUTPUT_/build_info.txt
          echo "Git commit: $(git rev-parse HEAD)" >> _OUTPUT_/build_info.txt
          echo "Git branch: $(git rev-parse --abbrev-ref HEAD)" >> _OUTPUT_/build_info.txt

      - name: Upload framework package
        uses: actions/upload-artifact@v4
        with:
          name: win98-quickinstall-framework
          path: win98-quickinstall-framework.zip
          
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: win98-quickinstall-output
          path: _OUTPUT_
          
      - name: Upload ISO if created
        uses: actions/upload-artifact@v4
        with:
          name: win98-quickinstall-iso
          path: win98-quickinstall.iso
          if-no-files-found: ignore