name: Build Installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'installer/anbui'

    - name: List contents after checkout
      run: |
        ls -la installer
        ls -la installer/anbui

    - name: Download and Setup Cross Compiler
      run: |
        # Baixa o cross compiler musl
        wget https://musl.cc/i486-linux-musl-cross.tgz || \
        wget https://more.musl.cc/9.2.1/i486-linux-musl/i486-linux-musl-cross.tgz || \
        wget https://build.archive.org/musl-cross/i486-linux-musl-cross.tgz

        # Extrai o cross compiler
        tar xf i486-linux-musl-cross.tgz

        # Adiciona o cross-compiler ao PATH
        echo "PATH=$PATH:$(pwd)/i486-linux-musl-cross/bin" >> $GITHUB_ENV

    - name: Build Installer
      run: |
        echo "Current directory before build:"
        pwd
        ls -la installer
        cd installer
        echo "Current directory after cd:"
        pwd
        ls -la
        chmod +x build.sh
        ./build.sh

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lunmercy-artifact
        path: installer/lunmercy
