name: Build Win98 QuickInstall

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Debug Submodules
      run: |
        echo "Listing current directory:"
        ls -la
        echo "Checking busybox directory:"
        ls -la busybox || echo "busybox directory not found"
        echo "Checking .gitmodules content:"
        cat .gitmodules || echo ".gitmodules not found"

    - name: Initialize and Update Submodules
      run: |
        git submodule init
        git submodule update --init --recursive
        git submodule status

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc-multilib \
          g++-multilib \
          nasm \
          mtools \
          dosfstools \
          syslinux \
          xz-utils \
          cpio \
          zip \
          autoconf \
          automake \
          libtool \
          flex \
          bison \
          libelf-dev \
          bc \
          ncurses-base

    - name: Create cross-compiler directory and setup terminfo
      run: |
        mkdir -p i486-linux-musl-cross/i486-linux-musl/share/terminfo/l
        # Procurar o arquivo linux em vários locais possíveis
        for path in \
          "/lib/terminfo/l/linux" \
          "/usr/lib/terminfo/l/linux" \
          "/usr/share/terminfo/l/linux" \
          "/etc/terminfo/l/linux"; do
          if [ -f "$path" ]; then
            cp "$path" i486-linux-musl-cross/i486-linux-musl/share/terminfo/l/
            break
          fi
        done
        # Verificar se o arquivo foi copiado
        if [ ! -f "i486-linux-musl-cross/i486-linux-musl/share/terminfo/l/linux" ]; then
          echo "Criando arquivo terminfo manualmente"
          touch i486-linux-musl-cross/i486-linux-musl/share/terminfo/l/linux
        fi

    - name: Initialize Environment
      run: |
        chmod +x init.sh
        ./init.sh

    - name: Build BusyBox
      run: |
        echo "Verificando conteúdo do diretório busybox:"
        ls -la busybox
        if [ ! -f "busybox/build.sh" ]; then
          echo "Criando script build.sh para busybox"
          cat > busybox/build.sh << 'EOF'
#!/bin/bash
make defconfig
sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
make -j$(nproc)
make install
EOF
          chmod +x busybox/build.sh
        fi
        cd busybox
        ./build.sh

    - name: Build Linux Kernel
      run: |
        cd linux
        cp ../buildscripts/linux_config.flp .config
        make -j$(nproc) bzImage
        cp arch/x86/boot/bzImage ../bzImage.flp
        cp ../buildscripts/linux_config.cd .config
        make -j$(nproc) bzImage
        cp arch/x86/boot/bzImage ../bzImage.cd

    - name: Build Components
      run: |
        for component in "dosfstools" "syslinux" "util-linux" "tiny-floppy-bootloader" "installer" "dosflop" "pciutils"; do
          echo "Building $component"
          if [ -d "$component" ]; then
            cd $component
            if [ ! -f "build.sh" ]; then
              echo "Warning: build.sh not found in $component"
              cd ..
              continue
            fi
            chmod +x build.sh
            ./build.sh
            cd ..
          else
            echo "Warning: Directory $component not found"
          fi
        done

    - name: Create Output Structure
      run: |
        OUTPUT=$PWD/__BIN__
        CDROOT=$OUTPUT/cdromroot
        mkdir -p "$CDROOT/bin"
        mkdir -p "$OUTPUT/tools"
        mkdir -p "$OUTPUT/mercypak"
        mkdir -p "$OUTPUT/_DRIVER_"
        mkdir -p "$OUTPUT/_EXTRA_DRIVER_"

    - name: Package Files
      run: |
        OUTPUT=$PWD/__BIN__
        CDROOT=$OUTPUT/cdromroot
        
        # Copy kernels and bootloaders
        cp bzImage.cd "$CDROOT/" || echo "Warning: bzImage.cd not found"
        cp tiny-floppy-bootloader/cdrom.img "$CDROOT/" || echo "Warning: cdrom.img not found"
        cp tiny-floppy-bootloader/floppy.img "$OUTPUT/" || echo "Warning: floppy.img not found"
        cp tiny-floppy-bootloader/floppy.img "$CDROOT/" || echo "Warning: floppy.img not found (CDROOT)"
        cp dosflop/dosflop.img "$OUTPUT/" || echo "Warning: dosflop.img not found"
        cp dosflop/dosflop.img "$CDROOT/" || echo "Warning: dosflop.img not found (CDROOT)"
        
        # Copy binaries and tools with error handling
        cp util-linux/OUTPUT/bin/* "$CDROOT/bin/" 2>/dev/null || echo "Warning: util-linux binaries not found"
        cp util-linux/OUTPUT/sbin/* "$CDROOT/bin/" 2>/dev/null || echo "Warning: util-linux sbin not found"
        for util in cfdisk sfdisk lsblk; do
          cp util-linux/$util "$CDROOT/bin/" 2>/dev/null || echo "Warning: $util not found"
        done
        
        for util in lspci setpci "pci.ids"; do
          cp pciutils/$util "$CDROOT/bin/" 2>/dev/null || echo "Warning: $util not found"
        done
        
        cp dosfstools/OUTPUT/sbin/* "$CDROOT/bin/" 2>/dev/null || echo "Warning: dosfstools binaries not found"
        
        # Copy remaining files
        cp supplement/syslinux.cfg "$CDROOT" 2>/dev/null || echo "Warning: syslinux.cfg not found"
        cp supplement/install.txt "$CDROOT/" 2>/dev/null || echo "Warning: install.txt not found"
        cp installer/lunmercy "$CDROOT/bin/" 2>/dev/null || echo "Warning: lunmercy not found"
        cp -r tools "$OUTPUT" 2>/dev/null || echo "Warning: tools directory not found"
        
        # Copy drivers and preparation files
        cp -r sysprep/* "$OUTPUT" 2>/dev/null || echo "Warning: sysprep files not found"
        cp -r win98-driver-lib-base/* "$OUTPUT/_DRIVER_" 2>/dev/null || echo "Warning: base drivers not found"
        cp -r win98-driver-lib-extra/* "$OUTPUT/_EXTRA_DRIVER_" 2>/dev/null || echo "Warning: extra drivers not found"
        cp README.md "$OUTPUT" 2>/dev/null || echo "Warning: README.md not found"

    - name: Create Release Archive
      run: |
        VERSION=$(git describe --tags --always)
        cd __BIN__
        zip -r "../Windows98QuickInstall_${VERSION}.zip" ./

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows98QuickInstall
        path: Windows98QuickInstall_*.zip
        retention-days: 90

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Windows98QuickInstall_*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
