name: Build Installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download anbui repository
      run: |
        mkdir -p installer/anbui
        cd installer/anbui
        git init
        git remote add origin https://github.com/altiereslima/anbui.git
        git fetch --depth=1 origin master
        git checkout FETCH_HEAD
        cd ../..

    - name: Download and Setup Cross Compiler
      run: |
        # Baixa o cross compiler musl
        wget https://musl.cc/i486-linux-musl-cross.tgz || \
        wget https://more.musl.cc/9.2.1/i486-linux-musl/i486-linux-musl-cross.tgz || \
        wget https://build.archive.org/musl-cross/i486-linux-musl-cross.tgz

        # Extrai o cross compiler
        tar xf i486-linux-musl-cross.tgz

        # Adiciona o cross-compiler ao PATH
        echo "PATH=$PATH:$(pwd)/i486-linux-musl-cross/bin" >> $GITHUB_ENV

    - name: Build Installer
      run: |
        echo "Current directory before build:"
        pwd
        ls -la installer
        cd installer
        echo "Current directory after cd:"
        pwd
        ls -la
        echo "Executing build.sh with debugging:"
        set -x
        chmod +x build.sh
        ./build.sh
        set +x

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lunmercy-artifact
        path: installer/lunmercy
