Run # Clona apenas os submódulos necessários
Submodule 'busybox' (git://git.busybox.net/busybox) registered for path 'busybox'
Cloning into '/home/runner/work/win98-quickinstall/win98-quickinstall/busybox'...
Submodule path 'busybox': checked out 'e512aeb0fb3c585948ae6517cfdf4a53cf99774d'
Submodule 'dosfstools' (https://github.com/dosfstools/dosfstools) registered for path 'dosfstools'
Cloning into '/home/runner/work/win98-quickinstall/win98-quickinstall/dosfstools'...
Submodule path 'dosfstools': checked out '2e866102d4378ea1ef5bdc02e11995018206f8af'
Submodule 'anbui' (git@github.com:oerg866/anbui.git) registered for path 'installer/anbui'
Cloning into '/home/runner/work/win98-quickinstall/win98-quickinstall/installer/anbui'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:oerg866/anbui.git' into submodule path '/home/runner/work/win98-quickinstall/win98-quickinstall/installer/anbui' failed
Failed to clone 'installer/anbui'. Retry scheduled
Cloning into '/home/runner/work/win98-quickinstall/win98-quickinstall/installer/anbui'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:oerg866/anbui.git' into submodule path '/home/runner/work/win98-quickinstall/win98-quickinstall/installer/anbui' failed
Failed to clone 'installer/anbui' a second time, aborting
Error: Process completed with exit code 1.
