name: Build Installer Only

on:
  push:
    branches:
      - master  # Altere para o nome da sua branch principal
  pull_request:
    branches:
      - master  # Altere para o nome da sua branch principal
  workflow_dispatch:  # Permite acionar o workflow manualmente

jobs:
  build-installer:
    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: false  # Desativa o checkout recursivo de submódulos

    - name: Clone necessary submodules manually
      run: |
        # Clona apenas os submódulos necessários
        git submodule update --init --recursive busybox
        git submodule update --init --recursive dosfstools
        git submodule update --init --recursive installer/anbui
        git submodule update --init --recursive linux
        git submodule update --init --recursive pciutils
        git submodule update --init --recursive util-linux
        git submodule update --init --recursive win98-driver-lib-base
        git submodule update --init --recursive win98-driver-lib-extra

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget bc bison flex libssl-dev libncurses-dev xz-utils cpio

    - name: Build the installer
      run: |
        # Navega para a pasta do instalador
        pushd installer
          chmod +x build.sh
          ./build.sh
        popd

    - name: Find and archive installer artifacts
      run: |
        # Procura por arquivos de saída na pasta do instalador
        mkdir -p artifacts
        find installer -type f \( -name "*.bin" -o -name "*.exe" -o -name "*.sh" -o -name "*.zip" \) -exec cp {} artifacts/ \;

        # Lista os arquivos encontrados (para depuração)
        echo "Artefatos encontrados:"
        ls -R artifacts/
        if [ -z "$(ls -A artifacts/)" ]; then
          echo "Nenhum artefato encontrado!"
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: installer-artifacts
        path: artifacts/
